#
# LevelTools v${version} by byteful#0001
#

# Useful Links:
# - https://minecraft.fandom.com/wiki/Attribute
# - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/attribute/Attribute.html
# - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
# - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html

# What action should be done when combining items in an anvil?
# Modes: "HIGHER_OF_BOTH" (Takes level and xp of higher level item), "LOWER_OF_BOTH" (Takes level and xp of lower level item), OR "ADD_BOTH" (Adds the level and XP of both items)
anvil_combine: "ADD_BOTH"

# The amount of XP needed to get from level 0 to level 1.
level_xp_start: 100.0

# The increase in amount of XP needed to get from level to level.
# Ex: If we are on level 1 and the level_xp_start is on 100.0 and the mode is ADD with 100.0, it would take 200.0 XP to get to level 2 from level 1.
# Ex 2: If we are on level 1 and the level_xp_start is on 100.0 and the mode is MULTIPLY with 2.0, it would take 200.0 XP to get to level 2 from level 1.
level_xp_increase:
  mode: "ADD" # Modes: "ADD" or "MULTIPLY"
  amount: 100.0

# Should blocks that are placed by a player count towards XP?
# May cause lag on a large server. Recommended to keep this true.
# If this is set to false, all blocks placed beforehand will be counted towards XP.
playerPlacedBlocks: true

# Configuration for the sound played during a level up.
level_up_sound:
  sound: "ENTITY_PLAYER_LEVELUP" # Set to null to disable this.
  pitch: 1.0
  volume: 1.0

# The default block XP modifier. Look at the configuration section below for a better explanation.
default_block_xp_modifier:
  min: 0.5
  max: 1.5

# The default combat XP modifier. Look at the configuration section below for a better explanation.
default_combat_xp_modifier:
  min: 1.0
  max: 2.5

# Configuration for specific block modifiers.
# These modifiers change the amount of XP a block gives. Set the min and max to the same value to disable the random range system.
block_xp_modifiers:
  DIAMOND_ORE:
    min: 5.0
    max: 10.0

# Configuration for specific entity (combat) modifiers.
# These modifiers change the amount of XP an entity gives. Set the min and max to the same value to disable the random range system.
combat_xp_modifiers:
  BLAZE:
    min: 5.0
    max: 7.5

# A list that prevents/allows the blocks listed from giving XP on break.
block_list_type: "BLACKLIST" # Types: WHITELIST, BLACKLIST (blacklist by default)
block_list:
  - "FIRE"
  - "SOUL_FIRE"
  - "CRIMSON_FUNGUS"
  - "BROWN_MUSHROOM"
  - "RED_MUSHROOM"
  - "CRIMSON_ROOTS"
  - "GRASS"
  - "TALL_GRASS"
  - "SEAGRASS"
  - "TORCH"
  - "FERN"
  - "LARGE_FERN"
  - "SUNFLOWER"
  - "CORNFLOWER"

# A list that prevents/allows the entities listed from giving XP on kill.
entity_list_type: "BLACKLIST" # Types: WHITELIST, BLACKLIST (blacklist by default)
entity_list:
  - "PLAYER"

# Configuration for the progress bar.
progress_bar:
  # The total amount of bars in the progress bar.
  total_bars: 50
  # The symbol used for the bar.
  bar_symbol: '|'
  # The symbol used to prefix the bar symbols.
  prefix_symbol: '['
  # The symbol used to suffix the bar symbols.
  suffix_symbol: ']'
  # The color for the prefix symbol.
  prefix_color: '8' # Do not include the '&'
  # The color for the suffix symbol.
  suffix_color: '8' # Do not include the '&'
  # The color for the achieved/completed bars.
  completed_color: 'e' # Do not include the '&'
  # The color for the remaining/placeholder bars.
  placeholder_color: '7' # Do not include the '&'

# Configuration for items to be handled by LevelTools.
item_profiles:
  # Any name can be used here. This name/identifier is for your own use.
  Pickaxes:
    # List of Bukkit materials for this item profile to apply to.
    types:
      - "DIAMOND_PICKAXE"
      - "GOLDEN_PICKAXE"
      - "IRON_PICKAXE"
      - "STONE_PICKAXE"
      - "NETHERITE_PICKAXE"
      - "WOODEN_PICKAXE"
    # The reward profile to apply to this item profile.
    reward_profile: "Pickaxes"
    # The display profile to apply to this item profile.
    display_profile: "Default"
    # The trigger for this profile to gain XP on its items.
    # Handlers:
    # - "BLOCK_BREAK" : Trigger fired when a block is broken with any of the items above.
    # - "ENTITY_KILL" : Trigger fired when an entity is killed with any of the items above.
    # - "RIGHT_CLICK_BLOCK" : Trigger fired when any item above is right-clicked on a block.
    # - "LEFT_CLICK_BLOCK" : Trigger fired when any item above is left-clicked on a block.
    # - "TILL" : Trigger fired when a hoe type item above is clicked on dirt/grass to turn it into farmland.
    # - "PATH" : Trigger fired when a shovel type item above is clicked on grass to turn it into grass path.
    # - "STRIP" : Trigger fired when an axe type item above is clicked on log to strip the 'bark'.
    xp_trigger: "BLOCK_BREAK"
    # The max level that items in this profile can achieve.
    max_level: 500

# Configuration for reward profiles. These profiles can easily be added to specific items to improve the ease of configuration.
reward_profiles:
  # Any name can be used here. This name/identifier will be used to add this profile to an item.
  # Handlers:
  # - "command" : Runs the command provided as the console. (Ex: "command say test") (Placeholders: {player} - The player who performed the level up.)
  # - "player-command" : Runs the command provided as the player. ("Ex: player-command say test") (Placeholders: {player} - The player who performed the level up.)
  # - "enchant" : Adds an enchantment to the tool. Overrides existing enchantments with the new level provided. (Ex: "enchant efficiency 1")
  # - "enchant2" : Does the same thing as "enchant" but doesn't override existing enchantments. (Ex: "enchant2 efficiency 1")
  # - "attribute" : Modifies an attribute on the tool. (Ex: "attribute generic.attack_speed 10") OR (Ex: "attribute GENERIC_ATTACK_SPEED 10")
  Pickaxes:
    1:
      - "enchant2 efficiency 1"
      - "command tell {player} Congratulations, {player}! You have reached level 1 on your item."
    2:
      - "enchant2 efficiency 2"
      - "command tell {player} Congratulations, {player}! You have reached level 2 on your item."

# Configuration for display profiles. These profiles can be added to items to modify their display text.
display_profiles:
  # Any name can be used here. This name/identifier will be used to add this profile to an item.
  # Placeholders:
  # - {level} : The item's level.
  # - {xp} : The item's xp.
  # - {max_xp} : The item's max XP needed to reach the next level.
  # - {progress_bar} : The progress bar text built with the configuration under 'progress_bar'.
  Default:
    # Configuration for the item's display name.
    item_name:
      enabled: false # Does LevelTools override the item's name?
      text: "Level: {level}"
    # Configuration for the actionbar text shown to the player.
    actionbar:
      enabled: true # Does LevelTools send actionbar text to the player when they trigger an XP event?
      text: "{progress_bar} &8[&e{xp}&6/&e{max_xp}&8]"
    # Configuration for the item's lore.
    item_lore:
      enabled: true # Does LevelTools override the item's lore?
      text:
        - ""
        - "&eLevel: &6{level}"
        - ""
        - "{progress_bar} &e{xp}&6/&e{max_xp}"
    # Set to true if item attributes should not be shown. Recommended to keep this true to prevent 'lore spam'.
    hide_attributes: true