name: LevelItems
version: '${version}'
main: me.byteful.plugin.levelitems.LevelItemsPlugin
author: byteful
description: A plugin that adds a leveling system to any item in Minecraft. Earn rewards for certain item levels.
api-version: 1.13